### ISSUE TITLE
Uninstantiated clientBundles

### ISSUE THREAD

**Issue by eastwood** [jameslnewell/tradie-v4#24]
https://github.com/jameslnewell/tradie-v4/blob/master/packages/tradie-webpack-config/index.js#L376

It looks like the `tradie-webpack-config` API has `clientBundles`, but does not provide an API to edit them. It appears to be a remnant from: https://github.com/jameslnewell/tradie/blob/master/src/api/webpack/createClientConfig.js#L25

**Comment by jameslnewell** [comment]
Hey man. Yeah sorry, I hadn't got round to updating that fn. I've also deprecated the package for now (there's a bunch of other good abstractions on top of webpack config - if you even need them). https://github.com/jameslnewell/tradie-v4/blob/next/docs/contributing.md

**Comment by eastwood** [comment]
No worries, The static template is a good reference point. For those of us still using `master`. Any suggestions on how to include additional files (i.e .eot) from `node_modules`.

**Comment by jameslnewell** [comment]
hmm doesn't look like it is excluding node_modules https://github.com/jameslnewell/tradie-v4/blob/master/packages/tradie-webpack-config/index.js#L316

**Comment by eastwood** [comment]
Yea, after some more debugging, it appears that the exclusion of some `nodeExternals` was interfering with pulling these dependencies down. Happy to close issue for now. Any updates when v4 will be stable?

**Comment by jameslnewell** [comment]
Tested the last few things and published. 🎉

Documentation is a bit rough/lacking... please ask questions and PR anything thats missing!!! The following examples may help if you're using the "official" templates.
https://github.com/jameslnewell/react-app-example
https://github.com/jameslnewell/react-static-site-example
