### ISSUE TITLE
Thoughts on SASS out of the box?

### ISSUE THREAD

**Issue by mattbourke** [jameslnewell/tradie-v4#29]
Hi @jameslnewell 
What is your thoughts on having tradie-4 support SASS out of the box? I know it's aimed towards styled components etc. 
Should we bother getting it to work with SASS or are we better off spending time getting older code over to styled components?
Thanks for your time.

**Comment by jameslnewell** [comment]
👋 Hey @mattbourke! I'd prefer not to add `sass` for a few of reasons:

- `node-sass` requires a binary
- `node-sass` version bumps are painful as binaries for older versions of nodejs aren't published so you have to upgrade the version of nodejs that your app supports when `node-sass` decides it is time, not when the project author decides
- `nib` are using a custom `importer` for module resolution
- I don't use `sass` anymore (`styled-components` ftw)

I'd def encourage finishing your migration, but if that's too much work you can either a) fork the offical version and just add the `sass-loader`, or b) compile your `sass` files to `css` as a separate build step.

**Comment by mattbourke** [comment]
Thanks for the response. 
I'll probably push for time to get our header and footer moved to styled components, we have no plans in place to upgrade them as they will **one day** be replaced.

**Comment by jameslnewell** [comment]
Could always just have a build step in the header-footer component to compile that one `sass` file to `css` before publishing it.
